name: Refresh search data
on: 
  push:
    branches: [ main, master ]
    paths: '**.spec'
  workflow_dispatch:

jobs:
  Refresh-Search-Data:

    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out RPM SPEC files repository
        uses: actions/checkout@v2
        with:
          path: fedora-spec

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 

      - name: Check out Python Scan script repository
        uses: actions/checkout@v2
        with:
          repository: audinux/parse-spec
          path: parse-spec

      - name: Scan SPEC files and generate metadata
        run: python parse-spec/main.py fedora-spec

      - run: echo "TODO Test the ouput non-empty, valid json ..."
      - run: mkdir output
      - run: mv search-data.json output/

      - name: Push the ouput to web site repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: output/
          destination-repository-name: 'audinux.github.io'
          destination-github-username: 'audinux'
          target-directory: 'packages/data'
          user-email: 'brunovern.a@gmail.com'
          user-name: 'BrunoVernay'
          commit-message: 'Search metadata update via GH Actions.'

      
